version: "3.8"

services:
  postgres:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=ignite
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentcar
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: rentcar
    volumes:
      - .:/app
    network_mode: host
volumes:
  pgdata:
    driver: local     